export enum ActionNames {
    USER_LOGIN = "USER_LOGIN",
    USER_REGISTER = "USER_REGISTER",
    USER_LOGOUT = "USER_LOGOUT",
    UPDATE_USER_SOCKET_DETAILS = "UPDATE_USER_SOCKET_DETAILS",
    UPDATE_USER_PROFILE_PICTURE = "UPDATE_USER_PROFILE_PICTURE",
    SET_SOCKET = "SET_SOCKET",
}
