version: "3"

services:
  database:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres

  fastapiserver:
    image: fastapi/multiplayer-games
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    depends_on:
      - database
    env_file:
      - .env
